(cl:in-package tello_dronet-msg)
(cl:export '(HEADER-VAL
          HEADER
          BATTERY_LOW-VAL
          BATTERY_LOW
          BATTERY_LOWER-VAL
          BATTERY_LOWER
          BATTERY_PERCENTAGE-VAL
          BATTERY_PERCENTAGE
          BATTERY_STATE-VAL
          BATTERY_STATE
          CAMERA_STATE-VAL
          CAMERA_STATE
          DOWN_VISUAL_STATE-VAL
          DOWN_VISUAL_STATE
          DRONE_BATTERY_LEFT-VAL
          DRONE_BATTERY_LEFT
          DRONE_FLY_TIME_LEFT-VAL
          DRONE_FLY_TIME_LEFT
          DRONE_HOVER-VAL
          DRONE_HOVER
          EM_OPEN-VAL
          EM_OPEN
          EM_SKY-VAL
          EM_SKY
          EM_GROUND-VAL
          EM_GROUND
          EAST_SPEED-VAL
          EAST_SPEED
          ELECTRICAL_MACHINERY_STATE-VAL
          ELECTRICAL_MACHINERY_STATE
          FACTORY_MODE-VAL
          FACTORY_MODE
          FLY_MODE-VAL
          FLY_MODE
          FLY_SPEED-VAL
          FLY_SPEED
          FLY_TIME-VAL
          FLY_TIME
          FRONT_IN-VAL
          FRONT_IN
          FRONT_LSC-VAL
          FRONT_LSC
          FRONT_OUT-VAL
          FRONT_OUT
          GRAVITY_STATE-VAL
          GRAVITY_STATE
          GROUND_SPEED-VAL
          GROUND_SPEED
          HEIGHT-VAL
          HEIGHT
          IMU_CALIBRATION_STATE-VAL
          IMU_CALIBRATION_STATE
          IMU_STATE-VAL
          IMU_STATE
          LIGHT_STRENGTH-VAL
          LIGHT_STRENGTH
          NORTH_SPEED-VAL
          NORTH_SPEED
          OUTAGE_RECORDING-VAL
          OUTAGE_RECORDING
          POWER_STATE-VAL
          POWER_STATE
          PRESSURE_STATE-VAL
          PRESSURE_STATE
          SMART_VIDEO_EXIT_MODE-VAL
          SMART_VIDEO_EXIT_MODE
          TEMPERATURE_HEIGHT-VAL
          TEMPERATURE_HEIGHT
          THROW_FLY_TIMER-VAL
          THROW_FLY_TIMER
          WIFI_DISTURB-VAL
          WIFI_DISTURB
          WIFI_STRENGTH-VAL
          WIFI_STRENGTH
          WIND_STATE-VAL
          WIND_STATE
))